### ISSUE TITLE
Crash when trying to view application properties. 

### ISSUE THREAD

**Issue by ShevT** [crdroidandroid/android_packages_apps_Settings#111]
Settings -> Apps -> Choose any -> Crash

```
02-08 20:40:14.099 21449 25806 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
02-08 20:40:14.099 21449 25806 E AndroidRuntime: Process: com.android.settings, PID: 21449
02-08 20:40:14.099 21449 25806 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at android.os.AsyncTask$4.done(AsyncTask.java:415)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:1013)
02-08 20:40:14.099 21449 25806 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Unknown component: ComponentInfo{com.google.android.settings.intelligence/com.google.android.settings.intelligence.modules.battery.impl.BatterySettingsContentProvider}
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at android.os.Parcel.createExceptionOrNull(Parcel.java:2429)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:2409)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2392)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:2334)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at android.content.pm.IPackageManager$Stub$Proxy.getComponentEnabledSetting(IPackageManager.java:7204)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at android.app.ApplicationPackageManager.getComponentEnabledSetting(ApplicationPackageManager.java:2802)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at com.google.android.settings.fuelgauge.DatabaseUtils.isContentProviderEnabled(Unknown Source:13)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at com.google.android.settings.fuelgauge.DatabaseUtils.getHistoryMap(Unknown Source:63)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at com.google.android.settings.fuelgauge.PowerUsageFeatureProviderGoogleImpl.getBatteryHistory(Unknown Source:5)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at com.android.settings.fuelgauge.BatteryChartPreferenceController.getBatteryLast24HrUsageData(BatteryChartPreferenceController.java:621)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at com.android.settings.applications.appinfo.AppBatteryPreferenceController$1.doInBackground(AppBatteryPreferenceController.java:180)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at com.android.settings.applications.appinfo.AppBatteryPreferenceController$1.doInBackground(AppBatteryPreferenceController.java:173)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at android.os.AsyncTask$3.call(AsyncTask.java:394)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        ... 4 more
02-08 20:40:14.099 21449 25806 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.getComponentEnabledSettingInternal(PackageManagerService.java:24601)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.getComponentEnabledSetting(PackageManagerService.java:24584)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:3307)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:8915)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:        at android.os.Binder.execTransactInternal(Binder.java:1179)
02-08 20:40:14.099 21449 25806 E AndroidRuntime:
```

**Comment by ShevT** [comment]
Confirmed on OnePlus 7T Pro and Redmi Note 8T

**Comment by garry-rogov** [comment]
I confirm. Build from today

**Comment by gwolf2u** [comment]
weird enough, just built and can't confirm
steps to reproduce?
from our launcher or how?

**Comment by garry-rogov** [comment]
> weird enough, just built and can't confirm steps to reproduce? from our launcher or how?

I synced. I'll try to build now.

https://drive.google.com/file/d/1Wufm-5nKmnOpZ4uqf5mF8vTo_c4tOZ-9/view?usp=sharing

**Comment by ShevT** [comment]
https://drive.google.com/file/d/1Kg_isdxPrwK-Qk1dxBmzB9Vtmq2xATvA/view?usp=sharing

**Comment by gwolf2u** [comment]
working here for some reason
is language set to english on your devices?
also can you try to see if working to open from setttings - apps

**Comment by neobuddy89** [comment]
This has been fixed in Settings app force push.
