### ISSUE TITLE
Settings> Storage > SD Card crashing everytime

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/android_packages_apps_Settings#25]
In unofficial 8.0 builds for lettuce, whenever I try to open Settings > Storage > SD Card, the app crashes. Here's the log for it

```
10-05 16:31:01.003  1101  2873 I ActivityManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.DEFAULT] dat=content://com.android.externalstorage.documents/root/9016-4EF8 typ=vnd.android.document/root (has extras)} from uid 1000

10-05 16:31:01.004  5223  5223 D AndroidRuntime: Shutting down VM

10-05 16:31:01.005  5223  5223 E AndroidRuntime: FATAL EXCEPTION: main

10-05 16:31:01.005  5223  5223 E AndroidRuntime: Process: com.android.settings, PID: 5223

10-05 16:31:01.005  5223  5223 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW cat=[android.intent.category.DEFAULT] dat=content://com.android.externalstorage.documents/root/9016-4EF8 typ=vnd.android.document/root (has extras) }

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1936)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5153)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at android.app.Activity.startActivityFromFragment(Activity.java:5129)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at android.app.Activity$HostCallbacks.onStartActivityFromFragment(Activity.java:7602)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at android.app.Fragment.startActivity(Fragment.java:1179)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at android.app.Fragment.startActivity(Fragment.java:1158)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at com.android.settings.deviceinfo.StorageSettings.onPreferenceTreeClick(StorageSettings.java:297)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at android.support.v7.preference.Preference.performClick(Preference.java:1124)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at android.support.v7.preference.Preference.performClick(Preference.java:1099)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at android.support.v7.preference.Preference$1.onClick(Preference.java:170)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at android.view.View.performClick(View.java:6256)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:24697)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6566)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)

10-05 16:31:01.005  5223  5223 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

10-05 16:31:01.007  1101  2882 W ActivityManager:   Force finishing activity com.android.settings/.Settings$StorageDashboardActivity

10-05 16:31:01.012  1101  1165 I ActivityManager: Showing crash dialog for package com.android.settings u0
```

*faced this issue in 3 clean builds (nothing added).

**Comment by gwolf2u** [comment]
as Oreo is still in development, please wait a little while for a proper fix
